### ISSUE TITLE
Camera Pose Format

### ISSUE THREAD

**Issue by N-McA** [alexsax/2D-3D-Semantics#12]
Is a more detailed description available for the camera pose format?

I was unable to determine how to transform from the point-cloud into camera coordinates.

One might assume that the usual application of the RT matrix would be sufficient, but it appears not. The T appears to be correct, but R does not align the axes appropriately in many images. I suspect this has something to do with the fields:

"camera_original_rotation" and "rotation_from_original_to_point" but their correct use is not apparent to me.

**Comment by N-McA** [comment]
Hey - yeah, if you could find it that would be very much appreciated!

**Comment by N-McA** [comment]
Or if there was a code block from the original work that might contain it, I wouldn't mind trawling through :)

**Comment by ir0** [comment]
From the last image, the top-view floorplan, I see that you are using the "aligned" version of the point clouds. This version is not the globally registered one, but instead follows the alignment procedure discussed in Section 3.2 "Canonical Coordinate System Among Spaces" in the paper "[3D Semantic Parsing of Large-Scale Indoor Spaces](http://buildingparser.stanford.edu/images/3D_Semantic_Parsing.pdf)". 

I am not sure what steps you are following to get the point clouds (there are different ways), but I can help you go back to the original version if you tell me which file you are using and from which dataset (S3DIS or 2D3DS). If you fix this you should not have any misalignment issues. If you still find any, please let us know.

**Comment by N-McA** [comment]
As suggested, this was due to the alignment procedure. I switched to loading the pointclouds from the .mat files included in the 2d-3d-s dataset and this immediately resolved the issue.

Loading the .mat files in python is not quite a one line operation; the (rather janky) code I used to do so is available in this gist: https://gist.github.com/N-McA/f8a34a46449994f8efbaef74c1536911

**Comment by cazhang** [comment]
I've got a question about the 'pose' as well: 
looking into the pano/pose folder, each json file holds 'camera_location' and 'camera_rt_matrix'. 
Just wondering what's the difference of 'camera_location' and the translation component of 'camera_rt_matrix'?

I'm also interested in how the camera pose of equirectangular images are extracted? Are they computed based on the camera poses of raw data, e.g. via different pitch and yaw values?
@alexsax maybe you can help

**Comment by MeatValley** [comment]
@cazhang the diference is just in which coordinate system they are. The camara location in the file is the location in the world frame, and the translation is in the cam frame. To check that just multiply the camara position for the rotation matrix (the first 3 columns of the RT matrix) and you will get the last column. In other words, they are the same thing, just in different coordinate system, and the conversion between them is the Rotation matrix.

**Comment by xuxiaoxxxx** [comment]
> @N-McA, do you solve this surface normal problem? Because I also encounter this and I don't know how to convert normal to camera coordinate.

Hi, do you slove this problem? I also don't know how to convert normal to camera coordinate. Can you share your covert code with me?

**Comment by TangKexin4646** [comment]
Could you please guide me on how to correctly access the globally registered version within the S3DIS dataset? @ir0
