### ISSUE TITLE
Questions about 3D Bbox 

### ISSUE THREAD

**Issue by Jiankai-Sun** [alexsax/2D-3D-Semantics#14]
Hi, Stanford team,

Firstly, thank you for providing such a great dataset (http://buildingparser.stanford.edu/dataset.html)!

We are confused about the provided Bbox coordinates of object stored in the 'Area_#/3d/pointcloud.mat' file.

In each object struct (Area --> Disjoint-Space --> object):

- object:        --> name: the name of the object, wiith per space indexing* (e.g. chair-1, wall_3, clutter_13, etc.)
                        --> points: the X,Y,Z coordinates of the 3D points that comprise this object
                        --> RGB_color: the raw RGB color value [0,255] associated with each point.
                        --> global_name: the name of the object, with per area global index**
                        --> Bbox: [Xmin Xmax Ymin Ymax Zmin Zmax] of the object's boudning box
                        --> Voxels: [Xmin Xmax Ymin Ymax Zmin Zmax] for each voxel in a 6x6x6 grid
                        --> Voxel_Occupancy: binary occupancy per voxel (0: empty, 1: contains points)
                        --> Points_per_Voxel: the object points that correspond to each voxel (in XYZ coordinates)

As described, [Xmin Xmax Ymin Ymax Zmin Zmax] is the object's bounding box. However, why are the coordinates of different objects are so similar as the attached screenshot shows. It seems like there are something wrong. Is there any other operations we need to do to get the correct 3D Bbox groundtruth? Could you please provide a specific README/Instructions to guide users correctly utilize the coordinates of 3D bounding box, both in world coordinate system and camera coordinate system?

Thank you for your reply!

**Comment by ir0** [comment]
Hi Jiankai,

From the screenshot you attached in the email you sent to us (attaching below for reference), I see that there is no problem with the values (in meters), however there seems to be an issue with the order of the variables. The variables should read: [Xmin Ymin Zmin Xmax Ymax Zmax]. Thanks for letting us know, we'll update the documentation. Let us know if this didn't work for you.

Best,
Iro

![bbox](https://user-images.githubusercontent.com/13407438/43083391-36de1a44-8e4b-11e8-9495-916ce6c836c9.jpg)

**Comment by Jiankai-Sun** [comment]
Thank you for your quick reply!

**Comment by Jiankai-Sun** [comment]
Oooh, other Questions:

1. What is the unit (e.g. in meters) of the `Bbox` in `pointcloud.mat` and the `camera_rt_matrix` in `Area_#/pano/pose/camera_0a70cd8d4f2b48239aaa5db59719158a_office_12_frame_equirectangular_domain_pose.json` file? 

2. I transform the `Bbox` from World Coordinate System to Camera Coordinate System as below:

- Get the coordinates of 8 cuboid corners (denoted by matrix <a href="https://www.codecogs.com/eqnedit.php?latex=M^{3\times8}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?M^{3\times8}" title="M^{3\times8}" /></a> ) from the provided `1x6 Bbox` in `pointcloud.mat`, `Area --> Disjoint-Space --> object --> Bbox`
-  Use the `camera_rt_matrix ` (denoted as <a href="https://www.codecogs.com/eqnedit.php?latex=N^{3\times&space;4}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?N^{3\times&space;4}" title="N^{3\times 4}" /></a>) in each `Area_#/pano/pose/camera_0a70cd8d4f2b48239aaa5db59719158a_$ROOM$_frame_equirectangular_domain_pose.json` file. 
- <a href="https://www.codecogs.com/eqnedit.php?latex=M^{4\times&space;8}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?M^{4\times&space;8}" title="M^{4\times 8}" /></a> is the matrix of corner coordinate after appending one row with 1 after the last row of <a href="https://www.codecogs.com/eqnedit.php?latex=M^{3\times8}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?M^{3\times8}" title="M^{3\times8}" /></a>
- Finally, I get the coordinate of each Bbox in camera coordinate system <a href="https://www.codecogs.com/eqnedit.php?latex=C^{3\times&space;8}&space;=&space;np.dot(N^{3\times&space;4},M^{4\times&space;8})" target="_blank"><img src="https://latex.codecogs.com/gif.latex?C^{3\times&space;8}&space;=&space;np.dot(N^{3\times&space;4},M^{4\times&space;8})" title="C^{3\times 8} = np.dot(N^{3\times 4},M^{4\times 8})" /></a>.

However, I visualize the Bbox (<a href="https://www.codecogs.com/eqnedit.php?latex=C^{3\times&space;8}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?C^{3\times&space;8}" title="C^{3\times 8}" /></a>) of objects in each room but the results look strange. E.g.

Figure 1:
![image](https://user-images.githubusercontent.com/25477396/43107893-e3eccd96-8e93-11e8-9de7-2c338f3e2342.png)

Figure 2:
![image](https://user-images.githubusercontent.com/25477396/43107916-fe362eb8-8e93-11e8-86ec-41a8ab83883b.png)

Figure 3:
![image](https://user-images.githubusercontent.com/25477396/43107927-0f660992-8e94-11e8-85c0-20a6d5f48aa8.png)

Figure 4:
![image](https://user-images.githubusercontent.com/25477396/43107953-28e8c60c-8e94-11e8-99e6-cb325c42369a.png)

Figure 1 & 4 are not aligned to axis. Even though some cuboid looks normal (Figure 2), the corresponding result is not correct if projected to panorama (Figure 3) provided in the dataset (`Area_# --> pano --> rgb --> camera_0a70cd8d4f2b48239aaa5db59719158a_$ROOM$_frame_equirectangular_domain_rgb.png`). probably because the corner coordinates of cuboid I obtained by  <a href="https://www.codecogs.com/eqnedit.php?latex=C^{3\times&space;8}&space;=&space;np.dot(N^{3\times&space;4},M^{4\times&space;8})" target="_blank"><img src="https://latex.codecogs.com/gif.latex?C^{3\times&space;8}&space;=&space;np.dot(N^{3\times&space;4},M^{4\times&space;8})" title="C^{3\times 8} = np.dot(N^{3\times 4},M^{4\times 8})" /></a> is wrong.

Do you have any suggestions to get the groundtruth coordinates of Bbox which can be projected to the rgb panorama provided in the 2D-3D-Semantic Dataset?

Thank you very much!
