### ISSUE TITLE
Surface normal from global coordinate to camera coordinate

### ISSUE THREAD

**Issue by fuenwang** [alexsax/2D-3D-Semantics#15]
Hi, thanks for releasing this amazing dataset.
From the README, the surface normal of equirectangular image is in global coordinate. But I want to calibrate them into camera coordinate. I have checked the pose file but the rotation in it seems not consistent with the coordinate. Could you tell me how to do this conversion?

Thanks!

**Comment by meder411** [comment]
Perhaps I'm oversimplifying, but I believe you just need to rotate the normals by the rotation matrix in the pose file. I'm also fairly sure the rotation about the vertical axis is all that matters as the cameras and world coordinate systems have similar XZ planes for indoor scenes.

**Comment by fuenwang** [comment]
Now, my way is to just ignore z-axis and the x-axis rotation in the file will be applied to minus y-axis rotation of the normal image, For now, they looks correct but I cannot sure about it.

**Comment by alexsax** [comment]
@meder411 Yes I think that's correct. The RT matrix in the JSON file came from Blender's `matrix_world`. I believe that is the matrix from camera coordinates -> global coordinates, and so using R transpose is exactly what you want @fuenwang.

Thanks @meder411!
