### ISSUE TITLE
Order of pose transformations to align EXR with back-projected camera points

### ISSUE THREAD

**Issue by meder411** [alexsax/2D-3D-Semantics#16]
I am trying to orient the back-projected pano pointclouds with the EXR ones. The pose file description is a little vague on the rotations and their order though.

I am confident that I've backprojected the points correctly (they are identical to the EXR pointclouds, just off by a rigid body transform).

Could you please articulate the rotation order concerning the two keys below:

```
"camera_original_rotation": #  The camera's initial XYZ-Euler rotation in the .obj, 
"camera_rt_matrix": #  The 4x3 camera RT matrix, stored as a list-of-lists,
```

Letting `camera_rt_matrix` be the 3x3 array R and the 3 array t and the `camera_original_rotation` be the 3x3 array `A`, how do I align the back-projected points with the EXR pointcloud?

`proj_pts` is the Nx3 points back-projected from the pano
`exr_pts` is the Nx3 points loaded from the EXR file

I don't understand what "`The camera's initial XYZ-Euler rotation in the .obj`" means. Where is that applied?

Typically, I'd have thought that 

```
transformed_proj_pts = np.matmul(R, proj_pts[...,None]).squeeze() + t
```

should do the trick. That's just applying the camera-coordinates-to-world-coordinates transform `R * X + t`. But the alignment is still off. I have to assume there is some application of the `A` matrix (`camera_original_rotation`) that I'm missing. I've spent a day trying various permutations and transposes of these transforms and visualizing the results, but I can't get the pointclouds aligned. What's the correct way to do this?

Note: my `A` matrix is formed as:

```
# eul is the 3-vector loaded from the 'camera_original_rotation'
phi = eul[0] 
theta = eul[1]
psi = eul[2]
ax = np.array([
	[1,0,0],
	[0, cos(phi), -sin(phi)],
	[0, sin(phi), cos(phi)]])
ay = np.array([
	[cos(theta), 0, sin(theta)],
	[0,1,0],
	[-sin(theta), 0, cos(theta)]])
az = np.array([
	[cos(psi), -sin(psi), 0],
	[sin(psi), cos(psi), 0],
	[0,0,1]])
A = np.matmul(np.matmul(az, ay), ax)
```

UPDATE: I ran a brute force approach where I computed all possible combinations and permutations of `+/-t`, `+/-c`, `R/R^T`, and `A/A^T`. None of them resulted in even a near-perfect match. I'm thoroughly confused.

**Comment by meder411** [comment]
For anyone else who struggled with this, the solution is:

```
x = ARAx' + c
```
For `x':=back-projected points`, `x:=exr points`, `A:=rotation matrix from Euler angles`, `R=rotation from Rt matrix`, and `c:=camera center`.

**Comment by anita94** [comment]
@meder411 Thanks a lot for the solution, I was really struggling with almost the same problem and your post really helped me!!
I just needed to rotate the points 90 degree more, in order to get what I needed

**Comment by nam1410** [comment]
Hi @meder411, Thank you for your explanation, it's very helpful. I have a follow-up question here, when you refer to the **adjusted camera coordinate system**, could you clarify what exactly that means? Are you implying there is an intermediate coordinate system between the camera coordinate and the world? It would help me better understand the transformation pipeline. Thanks!
