### ISSUE TITLE
How to correlate the pixel globalXYZ with the coordinates of pointclouds

### ISSUE THREAD

**Issue by Liusifei** [alexsax/2D-3D-Semantics#18]
Hi,

Thank you for releasing the amazing dataset.
I wonder what is the correct way to correlate the pixels in the RGB image, and the points in the point-cloud? e.g., to generate an index map which has the same size of the RGB image. Or, can I directly correlate the gloabalXYZ with the points' coordinates?

Thanks

**Comment by ir0** [comment]
Hi,

The globalXYZ images provide a correspondence between 3d points and RGB pixels, however these 3d points are unfortunately not the same as in the given point clouds. However, you can use the globalXYZ points to find the nearest point in the given point cloud, if you are interested in a correspondence between RGB pixels and the given 3D point cloud.
