### ISSUE TITLE
semantic_labels.json

### ISSUE THREAD

**Issue by mbaradad** [alexsax/2D-3D-Semantics#20]
The file does not seem to be in the assets folder on the repo. Should I get it from somewhere else?

**Comment by thbupt** [comment]
I hae the same question.

**Comment by alexsax** [comment]
@mbaradad thanks for making this issue! I think that we accidentally removed the file in the latest commit. I just pushed a new commit that includes `semantic_labels.json`.  If the file doesn't work for any reason, please feel free to reopen this issue :)

**Comment by mbaradad** [comment]
Thanks!
