### ISSUE TITLE
Re-voxelize at higher resolution

### ISSUE THREAD

**Issue by jlazarow** [alexsax/2D-3D-Semantics#22]
Hi,

It seems like the voxels are pretty low resolution (6x6x6) for objects? Are there particular reasons for this, and would it be plausible to re-voxelize to something higher like 64x64x64?

Thanks

**Comment by ir0** [comment]
Hi,

You can use any voxelization resolution you prefer. Both the instance-level segmented mesh and point cloud data are available with the dataset, which would permit you to do this operation.

**Comment by jlazarow** [comment]
Thanks, is there some code you can provide that performs this? I don't see how this is trivial given that everything in the dataset is very blender-specific and I've been unable to properly get the rendering to work. e.g. there are mistakes where the diffuse color is simply not present on the semantic.mtl and needs to be updated in some magic manner.
