### ISSUE TITLE
Accessing the different structs of pointcloud.mat

### ISSUE THREAD

**Issue by BjoernMichele** [alexsax/2D-3D-Semantics#23]
Thank you very much for providing the dataset. 

I am currently trying to access the data in the pointcloud.mat . Unfortunately I don't have access to matlab so I tried to open it with some HDF5 libraries with python but somehow I just got strange references, but no clear data structure (as can be seen in the screenshot in issue #14). Therefore my first  question is if you used besides Matlab another program/Library to access the pointlcoud.mat file ? 

As I am especially highly interested in the BBox data for the 3D point cloud I would also be interested if it is accessible also at another place (in the only 3D dataset I didn't find it)  ? 

Last question : The BBox parameter are estimated by looking at the pointcloud of the object and searching for the min/max values of this pointcloud for the different coordinates ?

**Comment by ir0** [comment]
**Access the Matlab file in other sources:** No, we haven't tried it in other programs/libraries.
**Bbox data:** This information is not contained elsewhere, however, as you pointed out, you can easily compute them by finding the min-max values per axis for each object. If you prefer to work on point clouds, you can find the corresponding data at the Stanford Large-Scale 3D Indoor Spaces Dataset (S3DIS) ([description](http://buildingparser.stanford.edu/dataset.html#Download), [download link](https://docs.google.com/forms/d/e/1FAIpQLScDimvNMCGhy_rmBA2gHfDu3naktRm6A8BPwAWWDv-Uhm6Shw/viewform?c=0&w=1)).
