### ISSUE TITLE
Missing rooms in 2D data

### ISSUE THREAD

**Issue by maxjaritz** [alexsax/2D-3D-Semantics#25]
Hi,
I found some rooms to be missing in the 2D data, especially for area 5, e.g. there are no images for area 5a, conferenceRoom_1. Why?

Thanks

**Comment by ir0** [comment]
**Area 5** is split in two parts: _area_5a_ and _area_5b_. The room _conferenceRoom_1_ exists in _area_5b_, that's why you cannot find data in area_5a but in area_5b's folder instead.
