### ISSUE TITLE
About clustering among image segments

### ISSUE THREAD

**Issue by ustundag** [alexsax/2D-3D-Semantics#27]
Dear researchers,

I want to find clusters among individual objects using only RGB and Semantic images. Can you share some approaches that help me achieve this task?

Thanks in advance.

**Comment by ir0** [comment]
Hi, 

If you are looking to find the same object instance across all images that contain it: given that all object instances have a unique ID, you can query if that unique ID exists or not in an image. Object instances are codified as color in the semantic images and you can use the assets/utils.py for a mapping between color and object instance. You can look at  #6 for an example of how to parse a semantic image into labels.

If this isn't what you are looking for, could you clarify what kind of clusters you are trying to find?

**Comment by ustundag** [comment]
Hi, Thank you for the quick reply.

I already know that and I'm planning to use only RGB and Semantic images where objects are assigned to a label.

I want to find how many different types of objects exist in an individual cluster. E.g. IKEA has labeled all `chair` objects just as you did and I will find how many different types of chairs are there in the cluster of `chair` .

I'm planning to crop and save all objects one by one from each RGB image, using semantic images as a mask for them. Then, I will apply clustering algorithms to the cluster of chairs. Does this approach make sense for you?

I'm an inexperienced student that's why I thought that your research experience may be beneficial for me in this case.

Thanks in advance.
