### ISSUE TITLE
About semantic labels

### ISSUE THREAD

**Issue by ghost** [alexsax/2D-3D-Semantics#28]
Hi,

Thank you very much for opening a great dataset.

Can I ask some questions?

I engage in a research about semantic segmentation of 3D point clouds by using 2D semantic labels based on camera pose.

So, what I want to obtain ( and I don't still obtain) are:

1. Ground truth of 3D semantic labels(may be semantic.mtl and semantic.obj? If so, Please let me know how to extract.)
2. Do /data/semantic or semantic_pretty/camera*.png  data mean 2D semantic labels? I want to know which object each label belongs to. Therefore, what I want is followed as:
[120, 120, 0] -> wall
[20, 40, 200] -> ceiling
.
.
.

I'm very happy that you respond.

**Comment by ustundag** [comment]
Hi,

Regarding your second question, maybe you can look at this issue; #6

**Comment by ir0** [comment]
Hi,

1. In each area_#/3d folder, you can find the corresponding semantic.obj and semantic.mtl files. The encoding is the same as the one for the semantic images, and you can follow a similar process to the next point.
2. As the previous comment pointed out, you can take a look at issue #6 for more information.

**Comment by ghost** [comment]
Dear researchers,

Thank you very much for your kind replies.

I succeeded to extract each pixel's class label.

Thank you very much !

**Comment by alexsax** [comment]
@AkiyoshiKurobe great! I'm closing this for now.

**Comment by ghost** [comment]
Thank you!
But, I have one question about 3D semantic labels. 
Do you have any solutions on obtain 3D semantic labels?
