### ISSUE TITLE
About 3d semantic label

### ISSUE THREAD

**Issue by ghost** [alexsax/2D-3D-Semantics#29]
Hi,

I engage in the research about 3d semantic segmentation.
So I want to evaluate my method in terms of accuracy for each point cloud.
What I want to obtain is 

(x, y, z, label)
(x, y, z, label)
.
.
.
.
..

I  would be very grateful if you could provide specific processing and code.

Thank you in advance.

Sincerely,
Akiyoshi

**Comment by alexsax** [comment]
Semantic annotations for the point clouds are available in the .mat files. See the README for an explanation of the structure of the .mat files. 

For semantic-segmentation evaluation code, the exact metric you want to use probably depends on your specific application.
