### ISSUE TITLE
2d Semantic segmentation labels

### ISSUE THREAD

**Issue by weixuansun** [alexsax/2D-3D-Semantics#30]
I am using the 2d semantic maps in the dataset, it is mentioned in the paper that 2d semantically label is projected from 3d semantic point cloud. 
Bur not sure how was this projection implemented detailedly, for example in the image below. 
![camera_08aa47684e3948558b6d23cdc7ec31b3_office_21_frame_3_domain_rgb](https://user-images.githubusercontent.com/13931546/62594842-67e9a180-b91f-11e9-81b1-bd4e496e130e.png)
![camera_08aa47684e3948558b6d23cdc7ec31b3_office_21_frame_3_domain_semantic_bookcase](https://user-images.githubusercontent.com/13931546/62594879-8b145100-b91f-11e9-976f-9403ed6d5ca9.jpg)
The white bookcase outside the door is not included in the label, it looks like an error annotation. I wonder is the point cloud outside the room not considered when generating 2d semantic label?

**Comment by alexsax** [comment]
The 2D semantic labels were created in Blender by rendering directly from the semantic mesh.
So long as the objects are unoccluded, they should be visible. 

How were these black + white images created? Also, could you provide the name of the corresponding RGB and semantic images?

**Comment by weixuansun** [comment]
Thank you for your quick reply, I found I made a mistake when I try to create a binary mask for a single class in an image. I will close the issue.
Btw, I wonder what is the efficient way to generate mask for one class in semantic map just like semantic-pretty? should we loop the colors in semantic_label.json to find matched color?
the above image's name is camera_08aa47684e3948558b6d23cdc7ec31b3_office_21_frame_3_domain_rgb.png

**Comment by ShihuaiXu** [comment]
I also want to know how to find matched color. Sir, have you solve this solution? @weixuansun

**Comment by weixuansun** [comment]
> I also want to know how to find matched color. Sir, have you solve this solution? @weixuansun

Hi, you can refer to this issue #6.

**Comment by cazhang** [comment]
> The 2D semantic labels were created in Blender by rendering directly from the semantic mesh.
> So long as the objects are unoccluded, they should be visible.
>
Is it possible to elaborate on how to make it work within Blender? :) 

I tried output 'material index' directly, but not able to get semantic labels. Am I missing something here? 
<img width="975" alt="image" src="https://user-images.githubusercontent.com/3361026/111041487-512afb00-8430-11eb-9d73-20c6c96681b6.png">
