### ISSUE TITLE
Rotations in the pose files

### ISSUE THREAD

**Issue by onatsahin** [alexsax/2D-3D-Semantics#31]
Hi,

My goal is to create range images from the point clouds using PCL. For that, I use the camera poses. However, the resulting range images are not showing where the corresponding RGB images do. Camera's location seems to be correct, but its pose is different. The closed issue https://github.com/alexsax/2D-3D-Semantics/issues/26 does what I want to do with the mesh, but I can't recreate this behavior with point clouds. I inferred that the Euler angles are given as radians. When creating the range images, I had to change the yaw angle by 90 or 180 degrees in the trials I made to make the camera look at where the corresponding rgb image shows. Even then, the resulting image does not perfectly align with the RGB image like it does in the closed issue I mentioned. What might be the issue? I am doing my experiments on Area 3, and I took the point cloud from the S3DIS dataset instead of the .mat file.

**Comment by brokenCandy** [comment]
@onatsahin  can I know how you generated images using camera poses and have you used python ?

**Comment by onatsahin** [comment]
@brokenCandy For creating the range images, I used PCL's RangeImagePlanar class. This class has a member function called createFromPointCloudWithFixedSize, which uses camera information and pose to create a range image from the point cloud. These are all available in the C++ version of PCL. PCL also has a python version with less functionality, but I'm not sure if the things I used are available there.

**Comment by lianghouhao** [comment]
@onatsahin Hi, may i ask whether you find the correct pose finally? How did you transform them in PCL? I loaded the .ply file and the position seems okay, but rotation was bad. Could you share how to input the pose of camera where the 3D view would look at the 2D image shows? thanks a lot
