### ISSUE TITLE
dataset access

### ISSUE THREAD

**Issue by anita94** [alexsax/2D-3D-Semantics#33]
Dear Alex,
I am using this dataset for my master thesis, and it's been almost a month that I cannot access the http://buildingparser.stanford.edu website, could you tell me what the issue is and whether it is going to be fixed anytime soon? 
Kind regards,
Anita

**Comment by ir0** [comment]
Hi Anita,

We are aware of the problem and we will fix it soon. In the meantime, you can use these links to download the datasets:

- S3DIS: [https://forms.gle/pVpoyW8H7iRbv6g8A](https://forms.gle/pVpoyW8H7iRbv6g8A)
- 2D3DS: [https://forms.gle/Jewfj2G4Yg4Xo8Wu7](https://forms.gle/Jewfj2G4Yg4Xo8Wu7)

**Comment by bonbonjour** [comment]
hello, ir0, have you download the s3dis, I can't download the dataset through the two website access above

**Comment by ir0** [comment]
Hi @bonbonjour - what seems to be the issue with downloading? BTW, S3DIS corresponds to the first link.

**Comment by bonbonjour** [comment]
how can I download 2D3DS database? the two link above is unaccessable, is there any other way to download the dataset? I'm in china. thanks!

**Comment by lapetite123** [comment]
hi, ir0, how can I download 2D3DS database? the two link above is unaccessable, is there any other way to download the dataset? I'm in china. thanks!

**Comment by ir0** [comment]
Unfortunately there aren't other links available. However, many researchers from China have been able to download it despite some initial problems.
