### ISSUE TITLE
I cannot access Dataset

### ISSUE THREAD

**Issue by sangrockEG** [alexsax/2D-3D-Semantics#37]
Hello.
To download the dataset, I filled in the following docs:
https://docs.google.com/forms/d/e/1FAIpQLScFR0U8WEUtb7tgjOhhnl31OrkEs73-Y8bQwPeXgebqVKNMpQ/viewform?c=0&w=1

After it, I got google cloud storage links for the XYZ and nonXYZ datasets, respectively.
(For your policy, I'll not write the links here...)

In the link, there were area_1.tar.gz, area_2.tar.gz, etc. 
But I could not download the files.
When I clicked the download button, it only gave me "Forbidden Error 403".

Is it somewhat caused by that I don't have permission yet?
I also tried the links in #33, but it also brings me to the same google cloud storage. 
Any help will be greatly appreciated.

**Comment by Hui-Yao** [comment]
I encountered the same question : (

**Comment by twmitchel** [comment]
This is still an issue.

@Alexandersax  @alexsax @ir0 
 Could you please resolve this or provide us with an alternative way of downloading the dataset?

**Comment by cv4aec** [comment]
Apologies for taking a bit of time to reply but there was an issue with our server. We migrated our data to another one, so if you follow the same process you should be able to download them now.

**Comment by ir0** [comment]
Apologies for taking a bit of time to reply but there was an issue with our server. We migrated our data to another one, so if you follow the same process you should be able to download them now.

**Comment by ghost** [comment]
Hi there,
this same issue also applies to the sub-dataset S3DIS, could you fix this as well?
Thank you!
