### ISSUE TITLE
Dataset is unable to be downloaded

### ISSUE THREAD

**Issue by jiajingchen113322** [alexsax/2D-3D-Semantics#48]
Hi ,
I tried to download the dataset, however, every time when it's almost finished, an error comes out. The error is shown below:
![image](https://user-images.githubusercontent.com/50345445/221453346-41f13bd2-77ed-494e-b317-d95b93950bbe.png)
Could you please help with this? thanks

**Comment by ir0** [comment]
We are aware of the issue and currently setting up a more accessible storage system. Please check back on the google form  for the updated links in 5-6 hours (the files are still uploading).
