### ISSUE TITLE
What's the differences between the area_*/3d/rgb.obj and area_*/3d/rgb_textures/*.obj?

### ISSUE THREAD

**Issue by zhixy** [alexsax/2D-3D-Semantics#7]
They looks almost identical to each other in meshlab

**Comment by alexsax** [comment]
Good catch. rgb.obj is just the other file renamed (via loading and saving out in Blender). Both contain the same information, though, so you can use either. Since rgb.obj is a standard name shared among all the areas, I recommend using it as the canonical file.

**Comment by zhixy** [comment]
Ok, got it. I have another question, the semantic.obj files include the labels, right? However, the label information is only supplied in the material name, are there any tools help me get the corresponding label of a image rendered from rgb.obj?

**Comment by alexsax** [comment]
Sorry about the long delay. I missed this! 
The labels are supplied in the material name, but the color from the semantic images can be interpreted as a 24-bit integer. This integer gives you an index into the array in `semantic_labels.json`, which contains the material name. 

If you have an rgb image rendered from rgb.obj, then you can use the corresponding semantic image to get the labels. If you are rendering images yourself, then you can use semantic.obj. Hope this helps!
