### ISSUE TITLE
Depths images look black

### ISSUE THREAD

**Issue by longlouisly** [alexsax/2D-3D-Semantics#8]
Thank you for providing such a great dataset. 
Question: In your sample [figure](https://raw.githubusercontent.com/alexsax/2D-3D-Semantics/master/assets/figure_1.jpg), the depth map looks smooth with many grayscale variations. However, when I view the data, most are black/white, with very little grayscale or smoothness. Is this intended or am I reading the pngs incorrectly?

**Comment by alexsax** [comment]
You're welcome! 
This is intended behavior! In the figure you linked, we used the log(depth) for visualization purposes. 
In the data, the images are 16-bit and so look black. They do contain the correct depth information, and for visualizing I recommend either using the log-depth or else rescaling the values linearly based on the max (nonmissing) depth in the image.

**Comment by longlouisly** [comment]
Thanks for your quick response. I also realize now that the missing values were set to white (255).

**Comment by alexsax** [comment]
Yeahp, missing values are set to the maximum possible value. Also, make sure that you're using 16-bit channels (and that the max value is 65535) so that you get the full depth resolution!
